import "../shared/resources/css/globals.css";
import localFont from "next/font/local";
import type { Metadata } from "next";
import MainLayout from "@/app/layouts/MainLayout";
import StoreProvider, { CustomerStoreProvider } from "@/app/shared/components/StoreProvider";

const playfairDisplayRegular = localFont({
  src: "../shared/resources/fonts/PlayfairDisplay-Regular.woff",
  variable: "--ff-pl-regular",
  weight: "400",
});
const playfairDisplayMedium = localFont({
  src: "../shared/resources/fonts/PlayfairDisplay-Medium.woff",
  variable: "--ff-pl-medium",
  weight: "500",
});
const playfairDisplaySemibold = localFont({
  src: "../shared/resources/fonts/PlayfairDisplay-SemiBold.woff",
  variable: "--ff-pl-semibold",
  weight: "600",
});
const playfairDisplayBold = localFont({
  src: "../shared/resources/fonts/PlayfairDisplay-Bold.woff",
  variable: "--ff-pl-bold",
  weight: "700",
});

// Roboto font definitions
const robotoRegular = localFont({
  src: "../shared/resources/fonts/Roboto-Regular.woff",
  variable: "--ff-ro-regular",
  weight: "400",
});
const robotoMedium = localFont({
  src: "../shared/resources/fonts/Roboto-Medium.woff",
  variable: "--ff-ro-medium",
  weight: "500",
});
const robotoBold = localFont({
  src: "../shared/resources/fonts/Roboto-Bold.woff",
  variable: "--ff-ro-bold",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplayRegular.variable} ${playfairDisplayMedium.variable} ${playfairDisplaySemibold.variable} ${playfairDisplayBold.variable} ${robotoRegular.variable} ${robotoMedium.variable} ${robotoBold.variable} antialiased`}
      >
        <CustomerStoreProvider>
          <MainLayout>{children}</MainLayout>
        </CustomerStoreProvider>
      </body>
    </html>
  );
}
