export const ROUTES = {
  HOME: "/",
  CATEGORY: "/category",
  CATEGORY_DETAIL: "/category/:id",
  PRODUCTS: "/product",
  PRODUCT_DETAIL: "/product/:id",
  CONTACT: "/contact",
  BLOG: "/blog",
  CART: "/cart",
  PROFILE: "/profile",
  AUTHEN: "/authen",
  CHECKOUT: "/checkout",
  COMPLETE: "/complete",
  ORDER: "/order",
};
