export const dataSource = [
  {
    key: "1",
    productName: "iPhone 14 Pro",
    category: "Smartphones",
    price: 999,
    stock: 45,
    discount: 0,
    totalValue: 44955,
    status: "publish",
    createdAt: "2024-01-15",
  },
  {
    key: "2", 
    productName: "Samsung Galaxy S23",
    category: "Smartphones", 
    price: 899,
    stock: 32,
    discount: 10,
    totalValue: 25891,
    status: "publish",
    createdAt: "2024-01-12",
  },
  {
    key: "3",
    productName: "MacBook Pro M2",
    category: "Laptops",
    price: 1499,
    stock: 12,
    discount: 0,
    totalValue: 17988,
    status: "publish", 
    createdAt: "2024-01-08",
  },
  {
    key: "4",
    productName: "Dell XPS 13",
    category: "Laptops",
    price: 1299,
    stock: 8,
    discount: 5,
    totalValue: 9872,
    status: "publish",
    createdAt: "2024-01-05",
  },
  {
    key: "5",
    productName: "iPad Air",
    category: "Tablets",
    price: 599,
    stock: 23,
    discount: 0,
    totalValue: 13777,
    status: "publish",
    createdAt: "2024-01-18",
  },
  {
    key: "6",
    productName: "AirPods Pro",
    category: "Audio",
    price: 249,
    stock: 56,
    discount: 0,
    totalValue: 13944,
    status: "publish",
    createdAt: "2024-01-10",
  },
  {
    key: "7",
    productName: "Sony WH-1000XM4",
    category: "Audio",
    price: 349,
    stock: 0,
    discount: 15,
    totalValue: 0,
    status: "unpublish",
    createdAt: "2024-01-03",
  },
  {
    key: "8",
    productName: "Apple Watch Series 8",
    category: "Wearables",
    price: 399,
    stock: 34,
    discount: 0,
    totalValue: 13566,
    status: "publish",
    createdAt: "2024-01-20",
  },
  {
    key: "9",
    productName: "Samsung Galaxy Watch 5",
    category: "Wearables",
    price: 279,
    stock: 18,
    discount: 5,
    totalValue: 4773,
    status: "publish",
    createdAt: "2024-01-14",
  },
  {
    key: "10",
    productName: "Nintendo Switch OLED",
    category: "Gaming",
    price: 349,
    stock: 0,
    discount: 0,
    totalValue: 0,
    status: "unpublish",
    createdAt: "2024-01-07",
  },
  {
    key: "11",
    productName: "PS5 Digital Edition",
    category: "Gaming",
    price: 399,
    stock: 5,
    discount: 0,
    totalValue: 1995,
    status: "publish",
    createdAt: "2024-01-16",
  },
  {
    key: "12",
    productName: "LG C2 OLED TV",
    category: "TVs",
    price: 1799,
    stock: 7,
    discount: 10,
    totalValue: 11333,
    status: "publish",
    createdAt: "2024-01-09",
  },
  {
    key: "13",
    productName: "Samsung QN90B",
    category: "TVs",
    price: 1599,
    stock: 4,
    discount: 5,
    totalValue: 6076,
    status: "publish",
    createdAt: "2024-01-11",
  },
  {
    key: "14",
    productName: "Bose QuietComfort 45",
    category: "Audio",
    price: 329,
    stock: 0,
    discount: 0,
    totalValue: 0,
    status: "unpublish",
    createdAt: "2024-01-04",
  },
  {
    key: "15",
    productName: "Microsoft Surface Laptop 5",
    category: "Laptops",
    price: 999,
    stock: 15,
    discount: 8,
    totalValue: 13786,
    status: "publish",
    createdAt: "2024-01-13",
  },
];

export const categories = [
  {
    label: "Smartphones",
    value: "Smartphones",
  },
  {
    label: "Laptops",
    value: "Laptops",
  },
  {
    label: "Tablets",
    value: "Tablets",
  },
  {
    label: "Audio",
    value: "Audio",
  },
  {
    label: "Wearables",
    value: "Wearables",
  },
  {
    label: "Gaming",
    value: "Gaming",
  },
  {
    label: "TVs",
    value: "TVs",
  },
];

export const discountCampaigns = [
  {
    label: "Summer Sale",
    value: "Summer Sale",
  },
  {
    label: "Black Friday",
    value: "Black Friday",
  },
  {
    label: "Cyber Monday",
    value: "Cyber Monday",
  },
  {
    label: "Holiday Sale",
    value: "Holiday Sale",
  },
];

export const statusOptions = [
  { label: "ACTIVE", value: "ACTIVE" },
  { label: "INACTIVE", value: "INACTIVE" },
];

